# Build settings
theme: jekyll-theme-slate
#markdown: kramdown
plugins:
  - jekyll-feed

# common settings
title: Random technical notes
email: pages.in@0503.info
author: Roman Okolovich
# Write an awesome description for your new site here. You can edit this line in _config.yml.
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  Random technical notes
baseurl: "" # the subpath of your site, e.g. /blog
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://pages.0503.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RvRom
github_username:  aurax

permalink: /:categories/:year/:month/:day/:title/

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# https://raw.githubusercontent.com/aurax/bazirus/master/docs/
avatar: images/logo.png


# Includes an icon in the footer for each username you enter
footer-links:
  github: aurax/bazirus
  linkedin: https://www.linkedin.com/in/romanok/
  twitter: RvRom

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

exclude:
  - LICENSE
  - README.md
  - CNAME
