call code --force --install-extension alefragnani.pascal
call code --force --install-extension alefragnani.pascal-formatter
call code --force --install-extension alexcvzz.vscode-sqlite
call code --force --install-extension bierner.markdown-checkbox
call code --force --install-extension blunt1337.todo-language
call code --force --install-extension DavidAnson.vscode-markdownlint
call code --force --install-extension donjayamanne.githistory
call code --force --install-extension eddy-r.purebasic-language
call code --force --install-extension EditorConfig.EditorConfig
call code --force --install-extension fernandoescolar.vscode-solution-explorer
call code --force --install-extension firefox-devtools.vscode-firefox-debug   
call code --force --install-extension formulahendry.code-runner
call code --force --install-extension GitHub.github-vscode-theme
call code --force --install-extension GitHub.vscode-pull-request-github
call code --force --install-extension go2sh.cmake-integration-vscode
call code --force --install-extension Gruntfuggly.todo-tree
call code --force --install-extension grzesiek110.teststory
call code --force --install-extension huizhou.githd
call code --force --install-extension jebbs.plantuml
call code --force --install-extension mathiasfrohlich.Kotlin
call code --force --install-extension mhutchie.git-graph
call code --force --install-extension ms-azuretools.vscode-docker
call code --force --install-extension ms-dotnettools.csharp
call code --force --install-extension ms-vscode-remote.remote-wsl
call code --force --install-extension ms-vscode.cmake-tools
call code --force --install-extension ms-vscode.cpptools
call code --force --install-extension ms-vscode.powershell
call code --force --install-extension msjsdiag.debugger-for-chrome
call code --force --install-extension PKief.material-icon-theme
call code --force --install-extension RandomFractalsInc.vscode-data-preview
call code --force --install-extension rogalmic.vscode-xml-complete
call code --force --install-extension ryu1kn.partial-diff
call code --force --install-extension sidneys1.gitconfig
call code --force --install-extension streetsidesoftware.code-spell-checker
call code --force --install-extension streetsidesoftware.code-spell-checker-russian
call code --force --install-extension sumneko.lua
call code --force --install-extension twxs.cmake
call code --force --install-extension Tyriar.shell-launcher
call code --force --install-extension vip20.vscode-agile-board
call code --force --install-extension vscode-icons-team.vscode-icons
call code --force --install-extension waderyan.gitblame
call code --force --install-extension wesbos.theme-cobalt2
call code --force --install-extension yzhang.markdown-all-in-one
